version: "2"
networks:
  signup-verification:
    driver: bridge
services:
  app:
    build: .
    environment:
      - REDIS_HOST=redis
    networks:
      - signup-verification
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    volumes:
      - ./src:/usr/src/app/src
  redis:
    image: redis:3.0.7
    networks:
      signup-verification:
        aliases:
          - redis
    volumes:
      - redis-data:/data
volumes:
  redis-data:
    driver: local
